### ISSUE TITLE
incorrect downloads path

### ISSUE THREAD

**Issue by vgainullin** [GeneDx/phenopy#38]
020-03-04 01:40:59,906 - phenopy - INFO - Incorrect url specified for HPO files: http://compbio.charite.de/jenkins/job/hpo.annotations.current/lastSuccessfulBuild/artifact/misc_2018/phenotype.hpoa

**Comment by arvkevi** [comment]
Let's update it to this link:
`http://compbio.charite.de/jenkins/job/hpo.annotations.current/lastStableBuild/artifact/current/phenotype.hpoa`

**Comment by arvkevi** [comment]
fixed in #41
